myrestaurant.o: myrestaurant.cpp Menu.h TableManagement.h
  g++ -c myrestaurant.cpp

menu.o: menu.cpp Menu.h
  g++ -c menu.cpp

TableManagement.o: TableManagement.cpp TableManagement.h
	g++ -c TableManagement.cpp

myrestaurant: myrestaurant.o menu.o TableManagement.o
  g++ myrestaurant.o menu.o TableManagement.o -o myrestaurant
